# Site _config.yml
#

# Locations
collections_dir: collections
# theme: minima
layout: empty

# Site defaults
us_url: https://onlyonelike.me
il_url: https://il.onlyonelike.me
title: Only One Like Me - Parents Meet Therapists
tagline: Build and manage the best care for your child
description: >- # this means to ignore newlines until "baseurl:"
  Parents and therapists meet. Build and manage the best care for your child 
  while utilizing your child rights and eligibilities and keeping your expenses under control  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://onlyonelike.me" # the base hostname & protocol for your site, e.g. http://example.com
email: info@onlyonelike.me
twitter_username: ool_me
author: ool_me
locale: en_US
og_image: https://onlyonelike.me/assets/i2/ooml-og-image.jpg
twitter_image: https://onlyonelike.me/assets/i2/ooml-og-image.jpg
twitter:
  username: ool_me
  card: summary_large_image
# facebook:
#  publisher: #FB page URL
#  admins: # user id of admin
#  app_id:
social:
  links:
    - http://twitter.com/ool_me
    # add FB, linkedin, instagram
  
# Branding
logo_alt: Only One Like Me
logo_transparent_50x: assets/i2/logo_tr_50px.png
logo: assets/i2/logo_tr_50px.png

collections:
  - slides

# Defaults for the pages and posts
defaults:
  - scope:
      path: "" # all files
    values:
      layout: empty
      title: Only One Like Me - Parents Meet Therapists
      tagline: Build and manage the best care for your child
      description: >- # this means to ignore newlines until "baseurl:"
        Parents and therapists meet. Build and manage the best care for your child 
        while utilizing your child rights and eligibilities and keeping your expenses under control  
      baseurl: "" # the subpath of your site, e.g. /blog
      url: "https://onlyonelike.me" # the base hostname & protocol for your site, e.g. http://example.com
      email: info@onlyonelike.me
      twitter_username: ool_me
      twitter:
        username: ool_me
        card: summary_large_image
      author: ool_me
      locale: en_US
      lang: en_US
      rtl: false
      og_image: https://onlyonelike.me/assets/i2/ooml-og-image.jpg
      image: https://onlyonelike.me/assets/i2/ooml-og-image.jpg
      twitter_image: https://onlyonelike.me/assets/i2/ooml-og-image.jpg
      logo: assets/i2/logo_tr_50px.png
      social:
        links:
          - http://twitter.com/ool_me
          # add FB, linkedin, instagram

#configure build
strict_front_matter: true

plugins:
  - jekyll-feed
  - github-pages-health-check
  - github-pages
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap

  # - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
 
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - library
   - manual
   - jekyll
   - scss
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/